//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpWoW.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpWoW.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add Light 的本地化字符串。
        /// </summary>
        internal static string AddLight {
            get {
                return ResourceManager.GetString("AddLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border 的本地化字符串。
        /// </summary>
        internal static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brush 的本地化字符串。
        /// </summary>
        internal static string Brush {
            get {
                return ResourceManager.GetString("Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brush radius: 的本地化字符串。
        /// </summary>
        internal static string BrushRadius {
            get {
                return ResourceManager.GetString("BrushRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camera sensitivity: 的本地化字符串。
        /// </summary>
        internal static string CameraSensitivity {
            get {
                return ResourceManager.GetString("CameraSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circle 的本地化字符串。
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explore flag (hex): 的本地化字符串。
        /// </summary>
        internal static string ExploreFlag {
            get {
                return ResourceManager.GetString("ExploreFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphics 的本地化字符串。
        /// </summary>
        internal static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load current 的本地化字符串。
        /// </summary>
        internal static string LoadCurrent {
            get {
                return ResourceManager.GetString("LoadCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent ID: 的本地化字符串。
        /// </summary>
        internal static string ParentID {
            get {
                return ResourceManager.GetString("ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save DBC 的本地化字符串。
        /// </summary>
        internal static string SaveDBC {
            get {
                return ResourceManager.GetString("SaveDBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Entry 的本地化字符串。
        /// </summary>
        internal static string SaveEntry {
            get {
                return ResourceManager.GetString("SaveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save folder: 的本地化字符串。
        /// </summary>
        internal static string SavePath {
            get {
                return ResourceManager.GetString("SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Special 的本地化字符串。
        /// </summary>
        internal static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the format you like to use for the depth and stencil buffer. The parameters are the following:
        ///D stands for depth and S stands for stencil, X means unused. Ideal is D24S8 which means 24 bits for depth and 8 bits for stencil. You can select the highest possible value, the lockable attribute is optional and you can ignore it. 的本地化字符串。
        /// </summary>
        internal static string StencilExplanation {
            get {
                return ResourceManager.GetString("StencilExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Worldmap 的本地化字符串。
        /// </summary>
        internal static string Worldmap {
            get {
                return ResourceManager.GetString("Worldmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 !!! WARNING: ADT are not correctly loaded in this mode !!! 的本地化字符串。
        /// </summary>
        internal static string WorldMapMinimapWarning {
            get {
                return ResourceManager.GetString("WorldMapMinimapWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WoW folder (effects on next start): 的本地化字符串。
        /// </summary>
        internal static string WoWFolder {
            get {
                return ResourceManager.GetString("WoWFolder", resourceCulture);
            }
        }
    }
}
